.TH exe\-thumbnailer 1 2017\-08\-12
.SH NAME
exe\-thumbnailer \- generate thumbnails from Windows executables
.SH SYNOPSIS
\fBexe\-thumbnailer\fR \fB<inputfile>\fR \fB<outputfile>\fR \fB<thumbnail URI>\fR
.SH DESCRIPTION
exe\-thumbnailer (formerly gnome\-exe\-thumbnailer) is a simple program that generates thumbnails for Windows executable files (.exe, .lnk, .msi, and .dll). It supports numerous file managers, including Nautilus, Caja, Nemo, Thunar (when Tumbler is installed), and PCManFM.
.SH "HOMEPAGE"
https://github.com/exe-thumbnailer/exe-thumbnailer
