.TH gnome\-exe\-thumbnailer 1 2015\-04\-28
.SH NAME
gnome\-exe\-thumbnailer \- generate thumbnails from Windows executables
.SH SYNOPSIS
\fBgnome\-exe\-thumbnailer\fR \fB<inputfile>\fR \fB<outputfile>\fR \fB<thumbnail URI>\fR 
.SH DESCRIPTION
gnome\-exe\-thumbnailer is a thumbnailer for Windows executable files that shows the embedded icons of .exe, .lnk, .msi, and .dll files when available, while giving the user a hint that Wine will be used to open it.
.SH "HOMEPAGE"
http://wiki.winehq.org/exe-thumbnailer